export interface Object {
    asignado: string,
    cve_cabms: string,
    consecutivo: number,
    descrip_bm: string,
    costo_bien: number,
    marca: string,
    modelo: string,
    serie: string,
    motor: string,
    descripcion: string,
    recursos: string,
    responsable: string,
    ubicacion: string,
    consumible: boolean,
}